server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/

spring:
  application:
    name: AUTH-SERVICE
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/jwt}           # Uses environment variable with a default
    username: ${SPRING_DATASOURCE_USERNAME:postgres} # Uses environment variable with a default
    password: ${SPRING_DATASOURCE_PASSWORD:postgres} # Uses environment variable with a default
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baselineOnMigrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${SPRING_DATASOURCE_USERNAME:postgres} # Uses environment variable with a default
    password: ${SPRING_DATASOURCE_PASSWORD:postgres} # Uses environment variable with a default
    repair: true
  web:
    resources:
      add-mappings: false

