server:
  port: 8761

eureka:
  instance:
    hostname: service-registry
    preferIpAddress: true
  server:
    enable-self-preservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF


spring:
  application:
    name: SERVICE-REGISTRY