server:
  port: 8222

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
    webclient:
      enabled: true
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:5173"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: quiz-service
          uri: lb://QUIZ-SERVICE
          predicates:
            - Path=/quiz/**
          filters:
            - AuthenticationFilter
        - id: question-service
          uri: lb://QUESTION-SERVICE
          predicates:
            - Path=/questions/**
          filters:
            - AuthenticationFilter
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

application:
  config:
    auth-url: http://auth-service:8083/auth/
