server:
  port: 8082
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: dolphin-mistral
          temperature: 0.7
  application:
    name: QUIZ-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/quizdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
application:
  config:
    question-url: http://localhost:8081/questions/

